config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show] do
    resources :ratings, only: [:show]
  end
  resources :progressions, only: [:index, :show] do
    post 'status' => 'progressions#status_update', as: :status_update
    resources :comment, only: [:index]
  end
  post 'comments/', to: 'comments#create'

  resources :charges

  get "/newtips", to: "pages#newtips"
  get "/price", to: "pages#price"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :comment
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :course

  has_many :answers, dependent: :destroy
  validates :message, presence: { not_blank: 'ne doit pas être vide' }
  validates :message, length: { minimum: 10, too_short: "Votre message doit faire au minimum 10 charactères" }
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :progressions, dependent: :destroy
  has_many :answers, through: :comments, dependent: :destroy
  has_many :users, through: :progression

  validates :title, presence: { not_blank: 'Humm... \'\' n\'est pas un bon titre ....' }
  validates :title, uniqueness: { not_uniq: 'Ce titre est déjà utilisé. Change !!!!'}
  validates :slug, uniqueness: { not_uniq: 'Ce slug est déjà utilisé. Fait gaff'}

end

app/models/progression.rb
class Progression < ApplicationRecord
  belongs_to :user
  belongs_to :course

  def status_visited_card
    return 'not-visited' if self.visited == false
  end

  def update_visite_status
    unless self.visited == true
      self.update!(visited: true)
    end
  end
end

app/models/progression_course.rb
class ProgressionCourse < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user

  validates :rate, presence: { not_blank: 'Si tu sais pas quoi mettre, lache-toi avec un 5 étoiles ...' }
  validates :rate, inclusion: { in: 0..5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
  has_many :progressions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :rating, dependent: :destroy
  has_many :order
  has_many :courses

  validates :first_name, :email, presence: { not_blank: 'Les champs sont vides... Applique toi !' }
  validates :email, uniqueness: true
  after_create :create_progression


  def create_progression
    Course.all.each do |course|
      Progression.create(user: self, course: course)
    end
  end

  def check_stripe_customer

  end



end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # after_action :redirect_course, only: [:create, :update, :destroy]

  def create
    @answer = authorize Answer.new(answer_params)
    @answer.user = current_user
    if @answer.save?
      redirect_to course_path(@answer.comment.course)
    else
      render :new
    end
  end

  def update
    @answer.update(answer_params)
    redirect_to course_path(@answer.comment.course)
  end

  def destroy
    @answer.destroy
    redirect_to course_path(@answer.comment.course)
  end

  private

  def find_answer
    @answer = authorize Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:message)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  before_action :authenticate_user!
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  # Pundit: white-list approach.
  # after_action :verify_authorized
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?, :raise => false

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized


  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  protected

  def after_sign_in_path_for(resource)
    progressions_path
  end

  def after_sign_up_path_for(resource)
    progressions_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :first_name, :last_name) }
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(params_comment)
    authorize @comment
    @comment.user = User.find(params[:user])
    @comment.course = Progression.find(params[:progression]).course
    if @comment.save
      redirect_to progression_path(Progression.find(params[:progression])), notice: "Votre commentaire a bien été posté"
    else
      redirect_to progression_path(Progression.find(params[:progression])), alert: "#{@comment.errors.messages[:message].first}"
    end
  end

  private

  def params_comment
    params.require(:comment).permit(:user, :course, :message)

  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :authenticate_user!, only: [:home, :newtips, :price]

  def home

  end

  def newtips

  end

  def price

  end

end

app/controllers/progressions_controller.rb
class ProgressionsController < ApplicationController
  before_action :progressions_user, only: [:index, :show]
  before_action :progression_user, only: [:show, :update]

  def index
    authorize @progressions
    @first_progression = @progressions.first
    @text_progressions = @progressions.offset(1).first(7)
    @business_progressions = @progressions.offset(8).first(10)
    @imbrication_progressions = @progressions.last(7)
  end

  def show
    @comment = Comment.new
    @comments = Comment.all.select{ |c| c.course == @progression.course}.sort_by{:created_at}
    @progression.update_visite_status
  end

  def status_update
    progression = Progression.find(params[:progression_id])
    authorize progression
    progression.update!(status: true)
    redirect_to progression_path(progression.id.to_i + 1)
  end

  private


  def params_progression
    params.require(:progression).permit(:status)
  end

  def progressions_user
    @progressions = policy_scope(Progression)
  end

  def progression_user
    @progression =  Progression.find(params[:id])
    authorize @progression
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def youtube_video(progression)
    render :partial => 'shared/video', :locals => { progression: progression}
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/progression_helper.rb
module ProgressionHelper
end

app/views/charges/create.html.erb
<div class="create-container">
  <div id="card-thanks-purchase">
    <h2>Ton paiement vient d'être effectué !</h2>
    <br>
    <h2>C'est maintenant que l'aventure Exceltips commence !</h2>
    <br>
    <h3>Déjà, un grand merci pour ta confiance.</h3>
    <br>
    <h4>Pour la suite, si tu as la moindre question n'hésite surtout pas à m'envoyer un mail ou à poster un commentaire dans le cours.</h4>
    <br>
    <h4>Maintenant, je t'invite à te créer un compte pour que tu puisse avoir accès à la plateforme</h4>
    <%= link_to "Me créer un compte", new_user_registration_path, class:"button-navbar" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Exceltips</title>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-139905266-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
    </script>
    <!-- END GOOGLE ANALYTICS -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- META TAGS -->
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <!-- END META TAGS -->
    <script>
        (function(h,o,t,j,a,r){
            h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
            h._hjSettings={hjid:1836061,hjsv:6};
            a=o.getElementsByTagName('head')[0];
            r=o.createElement('script');r.async=1;
            r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
            a.appendChild(r);
        })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
    </script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag asset_path('logo_exceltips.png') %>
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<nav id="navbar-home">
  <%= link_to root_path do %>
    <%= image_tag "logo_exceltips.png", class:"logo-avatar" %>
  <% end %>
  <div class="devise-button">
    <%= link_to 'Newsletter 📫', newtips_path, class:"not-active-link-home" %>
    <% if user_signed_in? %>
      <%= link_to 'Ma formation', progressions_path, class: 'button-navbar' %>
    <% else %>
      <%= link_to 'Se connecter', new_user_session_path, class: 'not-active-link-home' %>
      <button class="button-navbar purchase-button" id="checkout-button-price_HMAipK3IxRllNR" role="link">Acheter</button>
    <% end %>
  </div>
</nav>
<div id="banner-home">
  <div id="banner-home--title">
    <h1>2 heures pour apprendre Excel</h1>
    <h3>C'est tout ce qu'il vous faut.</h3>
    <button class="button-navbar purchase-button" id="checkout-button-price_HMAipK3IxRllNR" role="link">Rejoindre la formation</button>
  </div>
  <%= image_tag "detour_me_two.png" %>
</div>
<div id="statistic">
  <div id="udemy-subscriptions">
    <h3>+1000 inscriptions</h3>
    <%= image_tag 'udemy_logo.svg' %>
  </div>
  <div id="udemy-rating">
    <h3>Noté 4.5 sur 5</h3>
    <ul>
      <li class="star-rating"><i class="fas fa-star"></i></li>
      <li class="star-rating"><i class="fas fa-star"></i></li>
      <li class="star-rating"><i class="fas fa-star"></i></li>
      <li class="star-rating"><i class="fas fa-star"></i></li>
      <li class="star-rating"><i class="fas fa-star-half-alt"></i></li>
    </ul>
    <p>sur plus de 70 avis</p>
  </div>
</div>
<div id="social-proof">
  <h2 class="label-title">Ce que <span class="label-pointer">les élèves</span> en disent</h2>
  <div id="social-proof--images">
    <%= image_tag 'feedback-one.png', class:"img-feedback" %>
    <%= image_tag 'feedback-two.png', class:"img-feedback" %>
    <%= image_tag 'feedback-three.png', class:"img-feedback" %>
    <%= image_tag 'feedback-four.png', class:"img-feedback" %>
    <%= image_tag 'feedback-five.png', class:"img-feedback" %>
    <%= image_tag 'feedback-six.png', class:"img-feedback" %>
    <%= image_tag 'feedback-seven.png', class:"img-feedback" %>
    <%= image_tag 'feedback-eigth.png', class:"img-feedback" %>
    <%= image_tag 'feedback-nine.png', class:"img-feedback" %>
    <%= image_tag 'feedback-ten.png', class:"img-feedback" %>
  </div>
</div>
<div id="value-proposition">
  <h2 class="label-title">Pourquoi choisir <span class="label-pointer">Exceltips ?</span></h2>
  <h4><i class="fas fa-caret-right"></i> Une formation Excel qui va uniquement à l'essentiel</h4>
  <p>90% de vos tâches peuvent être rendues automatiques avec quelques formules Excel</p>
  <p>Avec la formation Exceltips, vous allez maîtriser ces fonctions Excel !</p>
  <h4><i class="fas fa-caret-right"></i> Une formation Excel 100% en ligne</h4>
  <p>Un espace personnel dédié où vous allez pouvoir poser vos questions et échanger avec les étudiants Exceltips</p>
  <p>Profitez d'être dans les transports en communs, le train pour vous améliorer sur Excel</p>
  <h4><i class="fas fa-caret-right"></i> Un apprentissage adapté à tous</h4>
  <p>Des fiches, ebook, exercices à télécharger et réaliser chez vous !</p>
  <p>Vous préférez le format vidéo ? Cela tombe bien, c'est inclus !</p>
  <h4><i class="fas fa-caret-right"></i> Qui vous a dit qu'il fallait des années ?</h4>
  <p>Deux heures, c'est ce qu'il vous faut avec Exceltips pour devenir productif sur Excel</p>
  <p>Fini les formations interminables pour un résultat incertain</p>
  <button class="button-navbar purchase-button" id="checkout-button-price_HMAipK3IxRllNR" role="link">Passer à Exceltips</button>
</div>
<div id="kind-student">
  <h2>Excel ne doit plus être un frein dans votre vie professionnelle</h2>
  <p>Si rien que le mot Excel vous fait frémir, que vous ne vous sentez pas à l'aise avec un tableur Excel ou que vous ne savez pas comment fonctionne une RechercheV</p>
  <strong><h6>La formation Exceltips est faite pour vous</h6></strong>
</div>
<div id="program-exceltips">
  <h2 class="label-title">Le<span class="label-pointer"> programme</span> de la formation Exceltips ?</h2>
  <h4>L'essentiel, rien d'autre.</h4>
  <ul>
    <li>
      <div class="card-course">
        <div class="card-course--left">
          <h4> Partie 1</h4>
          <h4>Les essentiels du Texte</h4>
        </div>
        <div class="card-course--right">
          <p><i class="far fa-check-circle"></i> Apprentissage des formules texte indispensable à maîtriser</p>
          <p><i class="far fa-check-circle"></i> Des vidéos explicatives</p>
          <p><i class="far fa-check-circle"></i> Des fiches à télécharger</p>
          <p><i class="far fa-check-circle"></i> Des exercices corrigés à réaliser</p>
        </div>
      </div>
    </li>
    <li>
      <div class="card-course">
        <div class="card-course--left">
          <h4> Partie 2</h4>
          <h4>Les essentiels business</h4>
        </div>
        <div class="card-course--right">
          <p><i class="far fa-check-circle"></i> Apprentissage des formules business indispensable à maîtriser</p>
          <p><i class="far fa-check-circle"></i> Des vidéos explicatives</p>
          <p><i class="far fa-check-circle"></i> Des fiches à télécharger</p>
          <p><i class="far fa-check-circle"></i> Des exercices corrigés à réaliser</p>
        </div>
      </div>
    </li>
    <li>
      <div class="card-course">
        <div class="card-course--left">
          <h4> Partie 3</h4>
          <h4>Utiliser Excel pour créer ses propres fichiers</h4>
        </div>
        <div class="card-course--right">
          <p><i class="far fa-check-circle"></i> Mettre en pratique les formules apprises pour automatiser ses propres fichiers</p>
          <p><i class="far fa-check-circle"></i> Des templates de tâches déjà automatisés</p>
          <p><i class="far fa-check-circle"></i> Des fiches explicatives</p>
        </div>
      </div>
    </li>
  </ul>
</div>
<div id="price-section">
  <h2 class="label-title">Quel est le <span class="label-pointer">prix</span></h2>
  <div class="card-price">
    <div id="label-promotion">
      <h5>-25%</h5>
    </div>
    <div class="card-price--header">
      <div class="card-price--header--price">
        <p>40€</p>
        <h2>30</h2>
        <h3>€</h3>
      </div>
      <h6>Accès à vie</h6>
    </div>
    <div class="card-price--body">
      <h6><i class="far fa-check-circle"></i><strong>  Accès à la formation Exceltips à vie</strong></h6>
      <h6><i class="far fa-check-circle"></i><strong>  Accès à la communeauté Exceltips</strong></h6>
      <h6><i class="far fa-check-circle"></i><strong>  Ebook +60 pages</strong></h6>
      <h6><i class="far fa-check-circle"></i><strong>  +15 vidéos explicatives</strong></h6>
      <h6><i class="far fa-check-circle"></i><strong>  +15 supports de cours téléchargeables</strong></h6>
      <h6><i class="far fa-check-circle"></i><strong>  +15 fichiers d'exercices pratiques</strong></h6>
    </div>
    <div class="card-price--footer">
      <button class="button-navbar purchase-button" id="checkout-button-price_HMAipK3IxRllNR" role="link">Me former avec Exceltips</button>
      <p>🔒Paiement sécurisé. 100% satisfait ou remboursé.</p>
    </div>
  </div>
</div>
<div id="student-section">
  <h2>Vous êtes étudiants ?</h2>
  <div>
    <h3>Bénéficiez de 25% de réduction !</h3>
    <h5>Pour bénéficier de l'offre, envoyez un mail à contact@exceltips.fr</h5>
  </div>
</div>
<div id="who-ami">
  <h2 class="label-title">Le formateur, <span class="label-pointer">Thomas Rodier</span></h2>
  <div id="who-ami--body">
    <%= image_tag 'me_detoure.png', id: "avatar-home", alt:"formateur-exceltips" %>
    <div id="who-ami--description">
      <span><i class="fas fa-caret-right"></i> <h5><strong>Contrôleur de gestion Reporting dans un groupe du CAC40</strong></h5></span>
      <span><i class="fas fa-caret-right"></i> <h5><strong>Contrôleur de gestion R&D dans un groupe du CAC40</strong></h5></span>
      <span><i class="fas fa-caret-right"></i> <h5><strong>Contrôleur de gestion dans une Startup</strong></h5></span>
      <span><i class="fas fa-caret-right"></i> <h5><strong>Développeur Freelance FullStack</strong></h5></span>
    </div>
  </div>
</div>
<div id="why-exceltips">
  <h2 class="label-title">Pourquoi avoir créé <span class="label-pointer">Exceltips ?</span></h2>
  <span><i class="fas fa-caret-right"></i> <h5><strong>Créer une formation qui me convient</strong></h5></span>
  <p>La vraie problématique que j'ai rencontrée lorsque j'ai commencé à me documenter sur Excel, c'est le nombre incalculable d'informations que l'on peut trouver sur internet.</p>
  <p>Et on s'y perd très facilement, on ne sait pas si les formules de calculs sont indispensable à apprendre ou si elles sont uniquement "gadgets".</p>
  <p>C'est pourquoi j'ai décidé de regrouper les formules que j'utilise tous les jours pour les regrouper dans une formation complète.</p>
  <span><i class="fas fa-caret-right"></i> <h5><strong>Maîtriser les fonctions de bases dès de le début de la vie active</strong></h5></span>
  <p>Lorsque j'ai intégré mon école de commerce, je pensais maîtriser les bases du logiciel Excel pour mon premier stage.</p>
  <p>Premier jour, la désilusion. Je n'étais même pas capable de comprendre ce que je voyais sur le fichier Excel.</p>
  <p>C'est également pour cette raison que j'ai créé Exceltips, Excel doit être un atout dans votre vie professionnelle !</p>
  <span><i class="fas fa-caret-right"></i> <h5><strong>Partager les connaissances que j'ai pu acquérir au plus grand nombre</strong></h5></span>
  <p>J'ai toujours voulu transmettre et aider !</p>
  <p>Cette formation c'est aussi un moyen pour moi de te partager tout ce que je peux savoir sur Excel et de t'en faire profiter.</p>
  <p>Grâce à cette formation, tu vas savoir utiliser les fonctions principales de Microsoft Excel</p>
</div>
<div id="callback-value">
  <h4>Une formation 100% en ligne</h4>
  <h5>Vous souhaitez gagner du temps ? Vous avez des questions ? Envoyez moi un mail à contact@exceltips.fr</h5>
</div>
<div id="faq-section">
  <h2 class="label-title">Questions fréquemment <span class="label-pointer">posées</span></h2>
  <div class="card-faq">
    <strong><h4>Jusqu'à quand ai-je accès à la formation ?</h4></strong>
    <strong><p>La formation est accessible à vie !</p></strong>
    <p>Vous profiterez également des nouveautés et des mises à jours de la formation</p>
  </div>
  <div class="card-faq">
    <strong><h4>Quel est le format de la formation</h4></strong>
    <strong><p>La formation est 100% en ligne !</p></strong>
    <p>Chaque section possède une vidéo explicative et du contenu téléchargeable</p>
  </div>
  <div class="card-faq">
    <strong><h4>Quel est le profil des participants?</h4></strong>
    <strong><p>Les participants sont principalement des personnes pour qui Excel est un problème</p></strong>
    <p>Mais à la suite de la formation, Excel sera un atout pour votre vie professionnelle</p>
  </div>
</div>
<div id="footer">
  <div id="footer--body">
    <%= image_tag 'logo_exceltips.png', class:"logo-avatar"%>
    <%= mail_to "contact@exceltips.fr", subject: "Thomas, j'ai une question à propos d'Exceltips" do %>
      <p><i class="fas fa-envelope"></i> Nous contacter</p>
    <% end %>
    <div id="footer--body--social">
      <h6>Nous suivre sur les réseaux</h6>
      <a href="https://www.facebook.com/exceltips.fr/"><i class="fab fa-facebook icon-footer"></i></a>
      <a href="https://www.instagram.com/exceltips.fr/"><i class="fab fa-instagram icon-footer"></i></a>
    </div>
  </div>
  <p>Fait avec <i class="fas fa-heart font-red"></i> à Paris - © 2019 - 2020 tous droits réservés Exceltips.fr</p>
</div>
<!-- MODAL -->
<!-- <div id="popup-leaving" tabindex="-1">
  <%#= render partial: "shared/form_sendinblue_popup" %>
</div> -->
<div class="promotional-banner-one">
  <h2>Pour célébrez la création de la plateforme Exceltips, <span>ÉCONOMISEZ -25%</span></h2>
  <button type="button" class="close" id="close-popup-promotion">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<script src="https://js.stripe.com/v3"></script>
<div id="error-message"></div>

app/views/pages/newtips.html.erb
<nav id="navbar-home">
  <%= link_to root_path do %>
      <%= image_tag "logo_exceltips.png", class:"logo-avatar" %>
    <% end %>
  <div class="devise-button">
    <%= link_to 'Newsletter 📫', newtips_path, class:"not-active-link-home" %>
    <% if user_signed_in? %>
      <%= link_to 'Ma formation', progressions_path, class: 'button-navbar' %>
    <% else %>
      <%= link_to 'Se connecter', new_user_session_path, class: 'not-active-link-home' %>
      <button class="button-navbar purchase-button" id="checkout-button-price_HMAipK3IxRllNR" role="link">Acheter</button>
    <% end %>
  </div>
</nav>
<div id="header-newtips">
  <h1>Vous souhaitez recevoir un tips tous les jours sur votre boîte mail ?</h1>
  <%= render partial: "shared/form_sendinblue_full_page" %>
</div>
<script src="https://js.stripe.com/v3"></script>
<div id="error-message"></div>

app/views/progressions/show.html.erb
<%= render partial: 'shared/navbar_dashboard', locals: { progression: @progression }  %>
<div class="wrapper-global">
  <%= render partial: 'shared/dashboard_two', locals: { progression: @progression, progressions: @progressions }  %>
  <div id="display-progression">
    <div id="progression-header">
      <h5 id="title-progression"><%= @progression.course.title %></h5>
      <% if @progression.status %>
        <span class="label done">Complété</span>
      <% else %>
        <span class="label undone">En cours</span>
      <% end %>
      <div class="progression-doc">
        <%= render partial: 'shared/file_course', locals: { progression: @progression } %>
        <%= render partial: 'shared/file_slip', locals: { progression: @progression } %>
        <%= render partial: 'shared/file_exercice', locals: { progression: @progression } %>
      </div>
    </div>
    <div id="progression-body">
      <% unless @progression.course.title[0..3] == "Imbr" %>
        <iframe class="video-youtube" src='https://www.youtube.com/embed/<%= @progression.course.video_id %>?rel=0&autoplay=<%= params[:autoplay] || 0 %>' frameborder='0' allowfullscreen></iframe>
      <% else %>
        <span class="video-youtube coming-soon"><h4>La vidéo arrive bientôt ! Je t'invite à télécharger le cours en attendant</h4></span>
      <% end %>
      <div class="progression-footer">
        <div class="add-comment-section">
          <div class="avatar-comment"><h3 ><%= current_user.first_name[0].upcase %></h3></div>
          <div class="create-comment-section">
            <%= simple_form_for @comment, url: comments_path(@comment, user: current_user, progression: @progression), method: 'post' do |f| %>
              <%= f.input :message,label: "Ecrire un message", type: 'text', input_html: { 'rows' => 4, placeholder: 'Wahou super cours ! Merci Thomas '} %>
              <%= f.button :submit, 'Poster', class:"active-navbar"%>
            <% end %>
          </div>
        </div>
        <div class="comments-section">
          <% @comments.each do |comment| %>
          <div class="card-comment">
            <h3 class="avatar-comment"><%= comment.user.first_name[0].upcase %></h3>
            <div class="comment-message">
              <p><strong><%= comment.user.first_name.capitalize %> <%= comment.user.last_name.first.capitalize %>.</strong></p>
              <p><%= l(comment.created_at, format: "%d %B %Y") %> </p>
              <span class="border-comment"><p><%= comment.message %></p></span>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_card_large.html.erb
<div class="card-large <%= progression.status_visited_card %>">
  <% if progression.course.cover.nil? || progression.course.cover.empty? || progression.course.cover == ""%>
    <img src="https://picsum.photos/seed/picsum/180/120" alt="">
  <% else %>
    <%= image_tag progression.course.cover %>
  <% end %>
  <div class="inside-card-large">
    <h6><%= progression.course.title %></h6>
    <p><%= progression.course.description %></p>
  </div>
  <div class="status-card">
    <% if progression.visited == false %>
      <i class="far fa-circle"></i>
    <% elsif progression.status == false %>
      <%= image_tag 'notdown.svg'%>
    <% else %>
      <i class="fas fa-check-circle"></i>
    <% end %>
  </div>
</div>

app/views/shared/_video.html.erb
<iframe width="490" height="275" src="<%= progression.course.video_url.first %>" frameborder="0" allowfullscreen></iframe>